### ISSUE TITLE
No programmatic association between visual label and textarea

### ISSUE THREAD

**Issue by cptvitamin** [pmitros/RateXBlock#1]
```
<div class="rate_header">What could be improved to make this section more clear?</div>
...
<textarea class="rate_freeform_area" rows="4" cols="30"></textarea>
```

There is no programmatic association between the visible label and the textarea.  Wrap or replace the parent element of the text node with a `<label for="[IDref]">` element with an IDref for the `<textarea>`

**Comment by pmitros** [comment]
Wrapped in a label.
