### ISSUE TITLE
No programmatic association between the visual text label and the group of radio buttons

### ISSUE THREAD

**Issue by cptvitamin** [pmitros/RateXBlock#2]
`<div class="rate_likert_header">Was this section clear or confusing?.</div>` 

Is not programmatically associated with the radiogroup.  Traditionally this is done by using `<fieldset>` and `<legend>`
 for example:

```
<fieldset>
<legend>Was this section clear or confusing?</legend>
[radiogroup]
</fieldset>
```

Alternatively, you can use the role=radiogroup and arialabelledby, like this:

```
<div role="radiogroup" aria-labelledby="radiolabel">
<div class="rate_likert_header" id="radiolabel">Was this section clear or confusing?.</div>
[radiogroup]
</div>
```

**Comment by pmitros** [comment]
Moved to fieldset+legend.
