### ISSUE TITLE
Screen readers reading unicode characters resulting in awkward UX

### ISSUE THREAD

**Issue by cptvitamin** [pmitros/RateXBlock#3]
Voiceover:
- Grinning face with Smiling Eyes
- Smiling face with Squinting Eyes
- Neutral face
- Frowning face
- Worried face

Chromevox:
- Grin
- Smile
- Deadpan face
- Frowning face
- Worried

I was about to find out what Windows screen readers say, but the test machine needed to go to tech support for some maintenance first.  I can repeat the test there if you are interested, but cleary, this is not a great user experience.  The offscreen text follows the unicode character, so both are announced.

**Comment by cptvitamin** [comment]
NVDA on Firefox
- Grinning face with Smiling Eyes
- Smiling face with Smiling Eyes
- Neutral face
- White frowning face
- Poor

Internet Explorer and JAWS
- [Nothing]
- [Nothing]
- [Nothing]
- Frowning Face
- [Nothing]

**Comment by pmitros** [comment]
_sigh_ Too bad. aria-hidden.
