### ISSUE TITLE
presence of title attribute triggering group role in Voiceover/Safari

### ISSUE THREAD

**Issue by cptvitamin** [pmitros/RateXBlock#5]
Voiceover has started "getting smarter" and has been adding "accessibility" roles to elements that have certain attributes (heuristics, not always a good thing).  I realized that when I used your XBlock with Voiceover, the `<label>` element had a role of group.  I did some tests and found that if the title attribute was not present this extra role announcement did not occur.  This is not a huge problem, but it did result in a lot of extra verbosity on the screen reader's part.  In Voiceover, this is extra inconvenient, because not only do you have to listen to the extra role announcement as well as the number of items contained, but you also have to use additional keystrokes to interact with the control: CTRL +  OPTION + SHIFT + Down Arrow to enter and then CTRL + OPTION + SHIFT + Up Arrow to exit.

I recommend NOT adding a title attribute to the label element.  You and I discussed this in person, and I recommended against using title all together, but if you must use it, I would limit it to the input element.

**Comment by pmitros** [comment]
We discussed in person. Conclusion was that we would not hack around a screenreader bug. The tooltip requires a title on the label. I removed the one from the input (which is the reverse of your recommendation).
