### ISSUE TITLE
Visual focus indicator for radio buttons is very poor if not non-existent and webkit does not allow keyboard focus at all

### ISSUE THREAD

**Issue by cptvitamin** [pmitros/RateXBlock#6]
Because the user agent typically applies the focus indicator to the radio button itself (not its label) and the radio button in this instance has an opacity of 0 and a width of 0 there is no indication of focus.  Firefox adds a yellow border to indicate which label has focus, but because the (4/5) smiley faces are yellow, the border is hardly perceptible at all.

worse yet, in webkit (safari and chrome) you cannot focus on the radio buttons at all with the keyboard.  Focus moves from the text area to the submit button.  This may indicate a severe limitation to your approach of using radio controls that have an opacity and width of zero.

**Comment by pmitros** [comment]
I added a CSS style so that the control has a border when focused. 

I was not able to replicate the focus issue under Chrome+Linux. Keyboard worked fine. However, I moved the controls to have a width of 1. Once I finish other issues, it'd be good to re-verify on Mac.
