### ISSUE TITLE
Submission feedback is not presented in an accessible manner

### ISSUE THREAD

**Issue by cptvitamin** [pmitros/RateXBlock#8]
The feedback provided to the user after form submission is dynamically inserted.  To force the screen reader to read the dynamically inserted text, it must be inserted into an aria live region:
`<div class="rate_thank_you" aria-live="polite">Thank you!</div>` 

For best compatibility, the live region itself should not be injected into the DOM, but should exist on page load and only the text node is added:

At page load:
`<div class="rate_thank_you" aria-live="polite"></div>` 

After submission
`<div class="rate_thank_you" aria-live="polite">Thank you!</div>`

**Comment by pmitros** [comment]
Done. Thank you!
